wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    code_path: code/homework1/train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1666075825.910865
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 23
      4: 3.10.6
      5: 0.13.4
      8:
      - 3
      - 5
activation:
  desc: null
  value: Relu
alias:
  desc: null
  value: 0
batch_size:
  desc: null
  value: 16
data_path:
  desc: null
  value: ./data
epochs:
  desc: null
  value: 100
gpuid:
  desc: null
  value: 0
hidden_dim:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.001
n_layers:
  desc: null
  value: 3
optimer:
  desc: null
  value: adam
save_path:
  desc: null
  value: ./result
wandb:
  desc: null
  value: true
